import Head from "next/head";
import Image from "next/image";
import DashBoard from "./dashboard";
import Login from "./login";
import { Provider } from "react-redux";
import store from "../src/app/store";
import { PersistGate } from "redux-persist/integration/react";
import { persistStore } from "redux-persist";
let persistor = persistStore(store);
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>pwd-restaurent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Provider store={store}>
          <PersistGate persistor={persistor}>
            <Login />
          </PersistGate>
        </Provider>
      </main>
    </div>
  );
}
